# Alacritty Config Files (TOML)
# See: https://toml.io/en/ 

# import: [~/.config/alacritty/catppuccin/catppuccin-mocha.toml]

# General properties
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless" # "Full" | "None" | "Transparent" | "Buttonless"
dynamic_padding = true 
opacity = 0.9

# [window.padding]
# x = 25
# y = 20

[font]
size = 16 

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"
