return {
	-- MIGRATION TO BLINK.CMP IN PROGRESS
	-- nvim-cmp main engine and LuaSnip disabled
	-- Sources temporarily kept for testing (will be removed once migration complete)

	-- DISABLED: Completion sources (being replaced by blink.cmp)
	-- {
	-- 	"hrsh7th/cmp-nvim-lsp",
	-- 	"hrsh7th/cmp-buffer",
	-- 	"hrsh7th/cmp-path",
	-- 	"hrsh7th/cmp-cmdline",
	-- 	"hrsh7th/cmp-nvim-lsp-signature-help",
	-- },

	-- DISABLED: Snippet engine and dependencies
	-- {
	-- 	"L3MON4D3/LuaSnip",
	-- 	event = "VeryLazy",
	-- 	version = "v2.*",
	-- 	dependencies = {
	-- 			"saadparwaiz1/cmp_luasnip",
	-- 	},
	-- },

	-- DISABLED: nvim-cmp main engine
	-- {
	-- 	"hrsh7th/nvim-cmp",
	-- 	"micangl/cmp-vimtex",
	-- 	config = function()
	-- 			local cmp = require("cmp")
	-- 			cmp.setup({
	-- 				snippet = {
	-- 					expand = function(args)
	-- 						require("luasnip").lsp_expand(args.body)
	-- 					end,
	-- 				},
	-- 				window = {
	-- 					completion = cmp.config.window.bordered(),
	-- 					documentation = cmp.config.window.bordered(),
	-- 				},
	-- 				mapping = cmp.mapping.preset.insert({
	-- 					["<C-b>"] = cmp.mapping.scroll_docs(-4),
	-- 					["<C-f>"] = cmp.mapping.scroll_docs(4),
	-- 					["<C-Space>"] = cmp.mapping.complete(),
	-- 					["<C-e>"] = cmp.mapping.abort(),
	-- 					["<CR>"] = cmp.mapping.confirm({ select = true }),
	-- 				}),
	--
	-- 				sources = cmp.config.sources({
	-- 					{ name = "nvim_lsp" },
	-- 					{ name = "luasnip" },
	-- 					{ name = "vimtex" },
	-- 					{ name = "nvim_lsp_signature_help", max_item_count = 5 },
	-- 					{
	-- 						name = "spell",
	-- 						max_item_count = 5,
	-- 						keyword_length = 3,
	-- 						option = {
	-- 							keep_all_entries = false,
	-- 							enable_in_context = function()
	-- 								return true
	-- 							end,
	-- 						},
	-- 					},
	-- 				}, {
	-- 					{ name = "buffer" },
	-- 				}),
	--
	-- 				experimental = {
	-- 					ghost_text = false,
	-- 				},
	-- 			})
	--
	-- 			cmp.setup.cmdline({ "/", "?" }, {
	-- 				mapping = cmp.mapping.preset.cmdline(),
	-- 				sources = {
	-- 					{ name = "buffer" },
	-- 				},
	-- 			})
	--
	-- 			cmp.setup.cmdline(":", {
	-- 				mapping = cmp.mapping.preset.cmdline(),
	-- 				sources = cmp.config.sources({
	-- 					{ name = "path" },
	-- 				}, {
	-- 					{ name = "cmdline" },
	-- 				}),
	-- 				matching = { disallow_symbol_nonprefix_matching = false },
	-- 			})
	-- 		end,
	-- 	},
}
